###############################################################################
#                          PHP nginx mariadb phpmyadmin                       #
###############################################################################
version:            "3.1"
services:
  webserver:
    image:          nginx:alpine
    hostname:       webserver
    container_name: corso-webserver
    working_dir:    /application
    networks:
      - traefik-proxy
    volumes:
      - .:/application
      - ./public:/usr/share/nginx/html
      - log-disk:/var/log/nginx
    ports:
      - 8080:80
      - 8443:443
volumes:
    log-disk:

networks:
  traefik-proxy:
    external: true
