# Simple docker-compose.yml
# You can change your port or volume location

version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    networks:
      - traefik-proxy
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kuma-secure.entrypoints=web-secure"
      # Serviamo kuma sotto il percorso /kuma:
      - "traefik.http.routers.kuma-secure.rule=Host(`odoo3.fasterweb.net`) && PathPrefix(`/kuma`)"
      # Rimuovo il percorso nell'invio
      - "traefik.http.middlewares.kuma-remove-path.stripprefix.prefixes=/kuma"
      # e aggiungo la regola ai middleware
      - "traefik.http.routers.kuma-secure.middlewares=kuma-remove-path"
      - "traefik.http.routers.kuma-secure.tls=true"
      - "traefik.http.routers.kuma-secure.tls.certresolver=le"
      - "traefik.http.routers.kuma-secure.service=kuma"
      - "traefik.http.services.kuma.loadbalancer.server.port=3001"
      - "traefik.docker.network=traefik-proxy"

networks:
  traefik-proxy:
    external: true
